pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Compile Java code
                    sh 'javac -g https://github.com/ShivrajGore/Jenkins-Zero-To-Hero/tree/main/my-java-project/HelloWorld.java'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Run Java program
                    sh 'java HelloWorld'
                }
            }
        }
    }
}
