pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Compile Java code
                    sh 'javac -g HelloWorld.java'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Run Java program
                    sh 'java HelloWorld'
                }
            }
        }
    }
}
